name: p2p_car_renting
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'
  flutter: '3.16.8'

dependencies:
  animated_size_and_fade:
    git: https://github.com/MohamadGreatWarrior/animated_size_and_fade

  auto_route: ^7.8.4

  bloc: ^8.1.2

  bloc_concurrency: ^0.2.3

  cached_network_image: ^3.3.1

  cloud_firestore: ^4.14.0

  collection: ^1.18.0

  const_date_time: ^1.1.0
  copy_with_extension: ^5.0.4

  dio: ^5.4.0

  dropdown_button2: ^2.3.9

  email_validator: ^2.1.17

  equatable: ^2.0.5

  firebase_auth: ^4.16.0

  firebase_core: ^2.24.2

  flash: ^3.1.0

  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3

  flutter_keyboard_visibility: ^6.0.0

  flutter_screenutil: ^5.9.0

  flutter_secure_storage: ^9.0.0

  flutter_spinkit: ^5.2.0

  flutter_staggered_animations: ^1.1.1

  flutter_svg: ^2.0.9

  get_it: ^7.6.7

  http: ^1.2.0

  injectable: ^2.3.2

  intl: ^0.17.0

  json_annotation: ^4.8.1

  lint: ^2.3.0

  local_auth: ^2.1.8

  logger: ^2.0.2+1

  meta: ^1.10.0

  permission_handler: ^11.2.0

  pretty_dio_logger: ^1.3.1

  rxdart: ^0.27.7

  shared_preferences: ^2.2.2

  simple_animations: ^5.0.2

  skeletonizer: ^1.0.1

  theme_tailor_annotation: ^2.0.2

  tuple: ^2.0.2
  wechat_assets_picker: ^8.8.1+1

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8
  copy_with_extension_gen: ^5.0.4
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  theme_tailor: ^2.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/

flutter_gen:
  output: lib/global/gen/

  integrations:
    flutter_svg: true

scripts:
  inspect: dart format . & flutter analyze

  clean: flutter clean ; flutter packages get

  build: dart run build_runner build --delete-conflicting-outputs

  watch: dart run build_runner watch --delete-conflicting-outputs

  splash: dart run flutter_native_splash:create

  icon: dart run flutter_launcher_icons